---
version: '3'

vars:
  COMMIT:
    sh: cat COMMIT
  API_URL: "https://api.github.com/repos/chubin/cheat.sh/commits"

tasks:
  debug:
    desc: desc
    cmds:
      - "docker buildx prune -af && docker system prune -af && BUILDKIT_PROGRESS=plain docker compose up --build"
  export:
    desc: Export the latest app commit to COMMIT
    cmds:
      - printf "%s" "{{ .COMMIT }}" > COMMIT
    vars:
      COMMIT:
        sh: curl -sX GET {{ .API_URL }} | jq --raw-output '.[0].sha'
  prune:
    desc: prune
    cmds:
      - docker system prune -af
  build:
    desc: build
    cmds:
      - docker compose up --build
  up:
    desc: up
    cmds:
      - docker compose up
  default:
    desc: List commands
    cmds:
      - task -l
    silent: true
